import dayjs from "dayjs";
import { Typography } from "@mui/material";
import { RHFSelect, RHFTextField } from "@root/components/hook-form";
import RHFDatePicker from "@root/components/hook-form/RHFDatePicker";
import SignaturePad from "@root/components/SignaturePad";

const todayDate = dayjs().format("MM/DD/YYYY");
export const CarerReferenceCheckDefaultValues = {
  p1Name: "",
  p1SentDate: new Date(todayDate),
  p1RecievedDate: new Date(todayDate),
  p1VerificationDate: new Date(todayDate),
  p1ReferenceDetails:"",
  s1Name: "",
  s1SentDate: new Date(todayDate),
  s1RecievedDate: new Date(todayDate),
  s1VerificationDate: new Date(todayDate),
  s1ReferenceDetails:"",
  p2Name: "",
  p2SentDate: new Date(todayDate),
  p2RecievedDate: new Date(todayDate),
  p2VerificationDate: new Date(todayDate),
  p2ReferenceDetails:"",
  s2Name: "",
  s2SentDate: new Date(todayDate),
  s2RecievedDate: new Date(todayDate),
  s2VerificationDate: new Date(todayDate),
  s2ReferenceDetails:"",
  prName: "",
  prSentDate: new Date(todayDate),
  prRecievedDate: new Date(todayDate),
  prVerificationDate: new Date(todayDate),
  prReferenceDetails:"",
  socialWorkerName: "",
  signed: "",
  date: new Date(todayDate),
  auditDate: new Date(todayDate),
  auditType: "",
  auditOutcome: "",
  participantsAudit: "",
  Agenda: "",
  recommendationsLevel: "",
  recommendationsType: "",
  meetingMinutes: "",
  details: "",
  updateMeetingRecord: null,
};

export const CarerReferenceCheckFormValues = [
  {
    gridLength: 12,
    heading: "Primary Carer Employment Reference 1 Checks",
    componentProps: {
      variant: "body2",
      fontSize: "16px",
      fontWeight: 600,
      color: "#343A40",
      sx: { mb: 4 },
    },
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Name",
      name: "p1Name",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Sent Date",
      name: "p1SentDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Recieved Date",
      name: "p1RecievedDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Verification Date",
      name: "p1VerificationDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 12,
    componentProps: {
      label: `Reference Details`,
      name: "p1ReferenceDetails",
      multiline: true,
      minRows: 3,
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 6,
  },
  {
    gridLength: 12,
    heading: "Secondary Carer Employment Reference 1 Checks",
    componentProps: {
      variant: "body2",
      fontSize: "16px",
      fontWeight: 600,
      color: "#343A40",
      sx: { mb: 4 },
    },
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Name",
      name: "s1Name",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Sent Date",
      name: "s1SentDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Recieved Date",
      name: "s1RecievedDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Verification Date",
      name: "s1VerificationDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 12,
    componentProps: {
      label: `Reference Details`,
      name: "s1ReferenceDetails",
      multiline: true,
      minRows: 3,
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 6,
  },
  {
    gridLength: 12,
    heading: "Primary Carer Employment Reference 2 Checks",
    componentProps: {
      variant: "body2",
      fontSize: "16px",
      fontWeight: 600,
      color: "#343A40",
      sx: { mb: 4 },
    },
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Name",
      name: "p2Name",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Sent Date",
      name: "p2SentDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Recieved Date",
      name: "p2RecievedDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Verification Date",
      name: "p2VerificationDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 12,
    componentProps: {
      label: `Reference Details`,
      name: "p2ReferenceDetails",
      multiline: true,
      minRows: 3,
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 6,
  },
  {
    gridLength: 12,
    heading: "Secondary Carer Employment Reference 2 Checks",
    componentProps: {
      variant: "body2",
      fontSize: "16px",
      fontWeight: 600,
      color: "#343A40",
      sx: { mb: 4 },
    },
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Name",
      name: "s2Name",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Sent Date",
      name: "s2SentDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Recieved Date",
      name: "s2RecievedDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Verification Date",
      name: "s2VerificationDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 12,
    componentProps: {
      label: `Reference Details`,
      name: "s2ReferenceDetails",
      multiline: true,
      minRows: 3,
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 6,
  },
  {
    gridLength: 12,
    heading: "Primary Carer Former Partner References Checks",
    componentProps: {
      variant: "body2",
      fontSize: "16px",
      fontWeight: 600,
      color: "#343A40",
      sx: { mb: 4 },
    },
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Name",
      name: "prName",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Sent Date",
      name: "prSentDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Recieved Date",
      name: "prRecievedDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label:"Verification Date",
      name: "prVerificationDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 12,
    componentProps: {
      label: `Reference Details`,
      name: "prReferenceDetails",
      multiline: true,
      minRows: 3,
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 6,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Name of Social Worker*",
      name: "socialWorkerName",
      fullWidth: true,
      select: true,
      sx: { mb: 4 },
    },
    options: [{ value: "diasabeledChoice", label: "Diasabeled Choice" }],
    component: RHFSelect,
    md: 6,
  },
  {
    gridLength: 6,
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "signed(supervising social worker)*",
      name: "signed",
    },
    component: SignaturePad,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Date",
      name: "date",
      sx: { mb: 4, mt:2  },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 12,
    hr: true,
  },
  {
    gridLength: 12,
    heading: "Audit Data",
    componentProps: {
      variant: "body2",
      fontSize: "16px",
      fontWeight: 600,
      color: (theme: any) => theme.palette.primary.main,
      sx: { mb: 4 },
    },
    component: Typography,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Date",
      name: "auditDate",
      sx: { mb: 4 },
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Type",
      name: "auditType",
      fullWidth: true,
      select: true,
      sx: { mb: 4 },
    },
    options: [{ value: "diasabeledChoice", label: "Diasabeled Choice" }],
    component: RHFSelect,
    md: 6,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Outcome",
      name: "auditOutcome",
      fullWidth: true,
      select: true,
      sx: { mb: 4 },
    },
    options: [{ value: "diasabeledChoice", label: "Diasabeled Choice" }],
    component: RHFSelect,
    md: 6,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Participants of Audit",
      name: "participantsAudit",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Agenda",
      name: "Agenda",
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 12,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Recommendations Level",
      name: "recommendationsLevel",
      fullWidth: true,
      select: true,
      sx: { mb: 4 },
    },
    options: [{ value: "diasabeledChoice", label: "Diasabeled Choice" }],
    component: RHFSelect,
    md: 6,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Recommendations Type",
      name: "recommendationsType",
      fullWidth: true,
      select: true,
      sx: { mb: 4 },
    },
    options: [{ value: "diasabeledChoice", label: "Diasabeled Choice" }],
    component: RHFSelect,
    md: 6,
  },
  {
    gridLength: 6,
    componentProps: {
      label: "Audit Meeting Minutes",
      name: "meetingMinutes",
      fullWidth: true,
      select: true,
      sx: { mb: 4 },
    },
    options: [{ value: "diasabeledChoice", label: "Diasabeled Choice" }],
    component: RHFSelect,
    md: 6,
  },
  {
    gridLength: 12,
    componentProps: {
      label: "Recommendation Details",
      name: "details",
      multiline: true,
      minRows: 3,
      sx: { mb: 4 },
    },
    component: RHFTextField,
    md: 6,
  },
  {
    gridLength: 6,
    uploadPhoto: true,
  },
];
