export const TableDemoData = [
  {
    id: 1,
    sNO: "1",
    applicantName: "Jamie",
    socialWorkerName: "John Doe ",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedby: "John Doe",
  },
  {
    id: 2,
    sNO: "2",
    applicantName: "Timmy Toppee",
    socialWorkerName: "Harriet Upp ",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedby: "JamesWatt",
  },
  {
    id: 3,
    sNO: "3",
    applicantName: "Timmy Toppee",
    socialWorkerName: "Anita Bath",
    createdDate: "12/10/2021",
    createdBy: "JamesWatt",
    modifiedDate: "26/12/2021",
    modifiedby: "John Doe",
  },
];
