export const tableMockData = [
  {
    id: "1",
    srNo: "1",
    childName: "John",
    dateTimeOfAccurance: "03/10/21 :: 11:00",
    childStatus: "ABC",
    createdDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "10/03/23",
    modifiedBy: "John Doe",
  },
  {
    id: "2",
    srNo: "2",
    childName: "John",
    dateTimeOfAccurance: "03/10/21 :: 11:00",
    childStatus: "XZY",
    createdDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "10/03/23",
    modifiedBy: "John Doe",
  },
  {
    id: "3",
    srNo: "3",
    childName: "John",
    dateTimeOfAccurance: "03/10/21 :: 11:00",
    childStatus: "ABCXYZ",
    createdDate: "03/10/21",
    createdBy: "JamesWatt",
    modifiedDate: "10/03/23",
    modifiedBy: "John Doe",
  },
];
