export const TableDemoData = [
  {
    id: 1,
    sNO: "1",
    NameOfApplicants: "Jamie",
    socialWorkerName: "John Doe ",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedBy: "John Doe",
  },
  {
    id: 2,
    sNO: "2",
    NameOfApplicants: "Timmy Toppee",
    socialWorkerName: "Harriet Upp  ",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedBy: "John Doe",
  },
  {
    id: 3,
    sNO: "3",
    NameOfApplicants: "Timmy Toppee",
    socialWorkerName: "Name Xame ",
    createdDate: "12/10/2021",
    createdBy: "JamesWatt",
    modifiedDate: "26/12/2021",
    modifiedBy: "John Doe",
  },
];
