import { RHFCheckbox, RHFSelect, RHFTextField } from "@root/components/hook-form";
import RHFDatePicker from "@root/components/hook-form/RHFDatePicker";
import RHFRadioGroupWithLabel from "@root/components/hook-form/RHFRadioGroupWithLabel";
import * as Yup from "yup";

export const ComplaintsInfoFormFields = [
  {
    id: 1,
    gridLength: 6,
    otherOptions: {
      name: "urnNumber",
      label: "URN Number",
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    id: 2,
    gridLength: 6,
    otherOptions: {
      name: "complaintAgainstPersonCategory",
      label: "Complaint Against Person Category",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 3,
    gridLength: 6,
    otherOptions: {
      name: "complaintAgainstPerson",
      label: "Complaint Against Person ",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 4,
    gridLength: 6,
    otherOptions: {
      name: "complaintDate",
      label: "Complaint Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    id: 5,
    gridLength: 6,
    otherOptions: {
      name: "agencyReportedDate",
      label: "Agency Reported Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    id: 6,
    gridLength: 6,
    otherOptions: {
      name: "reviewDate",
      label: "Review Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    id: 7,
    gridLength: 12,
    otherOptions: {
      name: "natureOfComplaint",
      label: "Nature of Complaint",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 8,
    gridLength: 6,
    otherOptions: {
      name: "personNotifiedAgency",
      label: "Person Notified to Agency",
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    id: 9,
    gridLength: 6,
    otherOptions: {
      name: "personCompletedReport",
      label: "Person Completing Report",
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    id: 10,
    gridLength: 6,
    otherOptions: {
      name: "agencySocialWorkerInvolved",
      label: "Agency Social Worker Involved",
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    id: 11,
    gridLength: 6,
    otherOptions: {
      name: "childLocalAuthority",
      label: "Child Local Authority",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 12,
    gridLength: 6,
    otherOptions: {
      name: "carerLocalAuthority",
      label: "Carer Local Authority",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 13,
    gridLength: 12,
    otherOptions: {
      name: "complaintDetails",
      label: "Complaint Details",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 14,
    gridLength: 12,
    otherOptions: {
      name: "investigationUndertaken",
      label: "Investigation Undertaken",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 15,
    gridLength: 12,
    otherOptions: {
      name: "independentSupportInfo",
      label: "Independent Support Offred Info",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 16,
    gridLength: 12,
    otherOptions: {
      name: "agencyActionTaken",
      label: "Agency Action Taken",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 17,
    gridLength: 12,
    otherOptions: {
      name: "complaintOutcome",
      label: "Complaint Outcome",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 18,
    gridLength: 6,
    otherOptions: {
      name: "isThisSubstained",
      label: "Is This Substained",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 19,
    gridLength: 12,
    otherOptions: {
      name: "teamManagerRecommendation",
      label: "Team Manager Recommendation",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 20,
    gridLength: 6,
    otherOptions: {
      label: "Has Registered Manager Informed",
      name: "hasRegisteredManagerInformed",
      options: ["Yes", "No"],
    },
    component: RHFRadioGroupWithLabel,
  },
  {
    id: 21,
    gridLength: 6,
    otherOptions: {
      name: "registeredManagerInformedDate",
      label: "Registered Manager Informed Date",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 22,
    gridLength: 6,
    otherOptions: {
      label: "Has Ofsted been Informed",
      name: "hasOfstedBeenInformed",
      options: ["Yes", "No"],
    },
    component: RHFRadioGroupWithLabel,
  },
  {
    id: 23,
    gridLength: 6,
    otherOptions: {
      name: "ofstedNotifiedDate",
      label: "Ofsted Notified Date",
      fullWidth: true,
      select: true,
    },
    options: [{ value: "nil", label: "nil" }],
    component: RHFSelect,
  },
  {
    id: 24,
    gridLength: 6,
    otherOptions: {
      label: "Is Schedule",
      name: "isSchedule",
      options: ["Yes", "No"],
    },
    component: RHFRadioGroupWithLabel,
  },
  {
    id: 25,
    gridLength: 12,
    otherOptions: {
      name: "reportedTo",
      label: "Reported To",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 26,
    gridLength: 12,
    otherOptions: {
      name: "registeredManagerRecommendation",
      label: "Registered Manager Recommendation",
      fullWidth: true,
      multiline: true,
      minRows: 2,
    },
    component: RHFTextField,
  },
  {
    id: 27,
    gridLength: 6,
    otherOptions: {
      name: "closureDate",
      label: "Closure Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    id: 28,
    gridLength: 6,
    otherOptions: {
      name: "nextAlertDate",
      label: "Next Alert Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
];
export const defaultValues = {
  urnNumber: null,
  complaintAgainstPersonCategory: null,
  complaintAgainstPerson: null,
  complaintDate: null,
  agencyReportedDate: null,
  reviewDate: null,
  natureOfComplaint: null,
  personNotifiedAgency: null,
  personCompletedReport: null,
  agencySocialWorkerInvolved: null,
  childLocalAuthority: null,
  carerLocalAuthority: null,
  complaintDetails: null,
  investigationUndertaken: null,
  independentSupportInfo: null,
  agencyActionTaken: null,
  complaintOutcome: null,
  isThisSubstained: null,
  teamManagerRecommendation: null,
  hasRegisteredManagerInformed: false,
  registeredManagerInformedDate: null,
  hasOfstedBeenInformed: false,
  ofstedNotifiedDate: null,
  isSchedule: false,
  reportedTo: null,
  registeredManagerRecommendation: null,
  closureDate: null,
  nextAlertDate: null,
  status: null,
};
export const formatters: any = {};

export const formSchema = Yup.object().shape({
  urnNumber: Yup.string().required("Required"),
  complaintAgainstPersonCategory: Yup.string().required("Required"),
  complaintAgainstPerson: Yup.string().required("Required"),
  complaintDate: Yup.date().required("Required"),
  agencyReportedDate: Yup.date().required("Required"),
  reviewDate: Yup.date().required("Required"),
  natureOfComplaint: Yup.string().required("Required"),
  personNotifiedAgency: Yup.string().required("Required"),
  personCompletedReport: Yup.string().required("Required"),
  agencySocialWorkerInvolved: Yup.string().required("Required"),
  childLocalAuthority: Yup.string().required("Required"),
  carerLocalAuthority: Yup.string().required("Required"),
  complaintDetails: Yup.string().required("Required"),
  investigationUndertaken: Yup.string().required("Required"),
  independentSupportInfo: Yup.string().required("Required"),
  agencyActionTaken: Yup.string().required("Required"),
  complaintOutcome: Yup.string().required("Required"),
  isThisSubstained: Yup.string().required("Required"),
  teamManagerRecommendation: Yup.string().required("Required"),
  hasRegisteredManagerInformed: Yup.string().required("Required"),
  registeredManagerInformedDate: Yup.date().required("Required"),
  hasOfstedBeenInformed: Yup.string().required("Required"),
  ofstedNotifiedDate: Yup.date().required("Required"),
  isSchedule: Yup.string().required("Required"),
  reportedTo: Yup.string().required("Required"),
  registeredManagerRecommendation: Yup.string().required("Required"),
  closureDate: Yup.date().required("Required"),
  nextAlertDate: Yup.date().required("Required"),
});
