import UkFlag from '../../../../../assets/svg/safeguarding/uk-flag.svg'

export const safeguardingRole = [
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: '',
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },{
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },{
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },{
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
];
