export const tableMockData = [
    {
      id: '1',
      srNo: '1',
      supervisingSocialWorker: 'Timmy Toppee',
      dateOfVisit: '03/10/21',
      visitType: 'Home Visit',
      visitStatus: 'Completed',
      category: 'A',
      createdDate: '03/10/21',
      createdBy: 'john doe',
    },
    {
      id: '1',
      srNo: '1',
      supervisingSocialWorker: 'Timmy Toppee',
      dateOfVisit: '03/10/21',
      visitType: 'Home Visit',
      visitStatus: 'Pending',
      category: 'A',
      createdDate: '03/10/21',
      createdBy: 'john doe',
    },
    {
      id: '1',
      srNo: '1',
      supervisingSocialWorker: 'Timmy Toppee',
      dateOfVisit: '03/10/21',
      visitType: 'Home Visit',
      visitStatus: 'Completed',
      category: 'A',
      createdDate: '03/10/21',
      createdBy: 'john doe',
    },
  ]