export const TableDemoData = [
  { id:1,
    case_id: "PDF",
    childName: "12.11.2021",
    incidentCategory: "Safeguarding policy",
    incidentDescriptionDocument: "Version_13.01_12112021",
    personInvolved: "Victor Krum (Safeguarding Officer)",
  },
  { id:1,
    case_id: "PDF",
    childName: "12.11.2021",
    incidentCategory: "Safeguarding policy",
    incidentDescriptionDocument: "Version_13.01_12112021",
    personInvolved: "Victor Krum (Safeguarding Officer)",
  },
  { id:1,
    case_id: "PDF",
    childName: "12.11.2021",
    incidentCategory: "Safeguarding policy",
    incidentDescriptionDocument: "Version_13.01_12112021",
    personInvolved: "Victor Krum (Safeguarding Officer)",
  },
  { id:1,
    case_id: "PDF",
    childName: "12.11.2021",
    incidentCategory: "Safeguarding policy",
    incidentDescriptionDocument: "Version_13.01_12112021",
    personInvolved: "Victor Krum (Safeguarding Officer)",
  },
]