export const fosterCarerData = [
  {
    id: "1",
    carerName: "Tom Hanks",
    childName: "Draco Malfoy",
    typeOfPlacement: "Long-Term",
    dateOfPlacement: "12-11-2022",
    placementEndDate: "23-07-2023",
    agencySocialWorker: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    laSocialWorker: "Remus Lupin",
    status: "Active",
    placementPlan: "",
    placementAgreements: "",
    approvedBy: "Sirius Black(Director)",
  },
  {
    id: "2",
    carerName: "Tom Hanks",
    childName: "Draco Malfoy",
    typeOfPlacement: "Long-Term",
    dateOfPlacement: "12-11-2022",
    placementEndDate: "23-07-2023",
    agencySocialWorker: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    laSocialWorker: "Remus Lupin",
    status: "Active",
    placementPlan: "",
    placementAgreements: "",
    approvedBy: "Sirius Black(Director)",
  },
  {
    id: "3",
    carerName: "Tom Hanks",
    childName: "Draco Malfoy",
    typeOfPlacement: "Long-Term",
    dateOfPlacement: "12-11-2022",
    placementEndDate: "23-07-2023",
    agencySocialWorker: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    laSocialWorker: "Remus Lupin",
    status: "Active",
    placementPlan: "",
    placementAgreements: "",
    approvedBy: "Sirius Black(Director)",
  },
];
