export const TableDemoData = [
  {
    id: 1,
    sNO: "1",
    carerName: "John Doe ",
    address: "Abc",
    approvalDate: "Xyz",
    approvalCategory: "Abc",
    childrenPlacements: "26/12/2021",
    totalVacancy: "1",
    availableVacancy: "1",
  },
  {
    id: 2,
    sNO: "2",
    carerName: "Harriet Upp ",
    address: "Abc",
    approvalDate: "Xyz",
    approvalCategory: "Abc",
    childrenPlacements: "26/12/2021",
    totalVacancy: "1",
    availableVacancy: "1",
  },
  {
    id: 3,
    sNO: "3",
    carerName: "Harriet Upp ",
    address: "Abc",
    approvalDate: "Xyz",
    approvalCategory: "Abc",
    childrenPlacements: "26/12/2021",
    totalVacancy: "1",
    availableVacancy: "1",
  },
];
