export const tableMockData = [
  {
    id: "1",
    srNo: "1",
    nameOfChild: "Timmy Toppee",
    dob: "10/07/23",
    supervisingSocialWorker: "Anne Teak",
    fosterCarer: "Teri Dactyl",
    signedDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "03/03/23",
    modifiedBy: "John Doe",
  },
  {
    id: "1",
    srNo: "1",
    nameOfChild: "Timmy Toppee",
    dob: "10/07/23",
    supervisingSocialWorker: "Anne Teak",
    fosterCarer: "Teri Dactyl",
    signedDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "03/03/23",
    modifiedBy: "John Doe",
  },
  {
    id: "1",
    srNo: "1",
    nameOfChild: "Timmy Toppee",
    dob: "10/07/23",
    supervisingSocialWorker: "Anne Teak",
    fosterCarer: "Teri Dactyl",
    signedDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "03/03/23",
    modifiedBy: "John Doe",
  },
];
