export const TableData=[
    {
        Sr_No: "01",
        Backup_File: "System Backup_30122021",
        Backup_type: "Monthly",
        CreatedDateTime: "Monthly",
        Full_Path: "/opt/Backup/System",
        Status: "Complete",
        Support_Ticket: "BACKUP-54785",
        Notifications: true,
      },
    {
        Sr_No: "02",
        Backup_File: "Daily Backup_12122021",
        Backup_type: "Monthly",
        CreatedDateTime: "Monthly",
        Full_Path: "/opt/Backup/System",
        Status: "In Progress",
        Support_Ticket: "BACKUP-54785",
        Notifications: true,
      },
    {
        Sr_No: "03",
        Backup_File: "Daily Backup_12122021",
        Backup_type: "Monthly",
        CreatedDateTime: "Monthly",
        Full_Path: "/opt/Backup/System",
        Status: "Backup Corrupted",
        Support_Ticket: "BACKUP-54785",
        Notifications: false,
      },
    {
        Sr_No: "04",
        Backup_File: "Daily Backup_12122021",
        Backup_type: "Monthly",
        CreatedDateTime: "Monthly",
        Full_Path: "/opt/Backup/System",
        Status: "Backup Interrupted",
        Support_Ticket: "BACKUP-54785",
        Notifications: false,
      },
]