export const fosterCarerData = [
  {
    id: "1",
    childName: "Draco Malfoy",
    carerNameFrom: "Tom Hanks",
    carerNameTo: "Tom Hanks",
    dateOfTransfer: "12-11-2022",
    transferReport: "",
    approvedBy: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    localAuthoritySw: "London Borough of Bexley",
    status: "Active",
  },
  {
    id: "2",
    childName: "Draco Malfoy",
    carerNameFrom: "Tom Hanks",
    carerNameTo: "Tom Hanks",
    dateOfTransfer: "12-11-2022",
    transferReport: "",
    approvedBy: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    localAuthoritySw: "London Borough of Bexley",
    status: "Active",
  },
  {
    id: "3",
    childName: "Draco Malfoy",
    carerNameFrom: "Tom Hanks",
    carerNameTo: "Tom Hanks",
    dateOfTransfer: "12-11-2022",
    transferReport: "",
    approvedBy: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    localAuthoritySw: "London Borough of Bexley",
    status: "Active",
  },
];
