

export const CHILD_PERSONAL_GOALS_MOCK_DATA = [
  {
    // srNo: 1,
    id: 1,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 2,
    id: 2,
    childId: "12",
    childFullName: "ggg",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 3,/
    id: 3,
    childId: "12",
    childFullName: "helo",
    goalName: "iii",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 4,
    id:4,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 5,
    id: 5,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 6,
    id: 6,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 7,
    id: 7,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 8,
    id: 8,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 9,
    id: 9,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 10,
    id: 10,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 11,
    id: 11,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 12,
    id: 12,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 13,
    id: 13,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
  {
    // srNo: 14,
    id: 14,
    childId: "12",
    childFullName: "helo",
    goalName: "helo",
    status: "helo",
    date: new Date(),
    comments: "sdsd",
  },
];


