export const fosterCarerData = [
  {
    id: "1",
    childName: "Draco Malfoy",
    primaryCarer: "Tom Hanks",
    respiteCarerName: "Tom Hanks",
    respiteStartDate: "12-11-2022",
    respiteEndDate: "12-11-2022",
    respitePlan: "",
    approvedBy: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    localAuthoritySw: "London Borough of Bexley",
    status: "Active",
  },
  {
    id: "2",
    childName: "Draco Malfoy",
    primaryCarer: "Tom Hanks",
    respiteCarerName: "Tom Hanks",
    respiteStartDate: "12-11-2022",
    respiteEndDate: "12-11-2022",
    respitePlan: "",
    approvedBy: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    localAuthoritySw: "London Borough of Bexley",
    status: "Active",
  },
  {
    id: "3",
    childName: "Draco Malfoy",
    primaryCarer: "Tom Hanks",
    respiteCarerName: "Tom Hanks",
    respiteStartDate: "12-11-2022",
    respiteEndDate: "12-11-2022",
    respitePlan: "",
    approvedBy: "Albus Dumbledore",
    localAuthority: "London Borough of Bexley",
    localAuthoritySw: "London Borough of Bexley",
    status: "Active",
  },
];
