import {
  RHFCheckbox,
  RHFSelect,
  RHFTextField,
} from "@root/components/hook-form";
import * as Yup from "yup";
import RHFDatePicker from "@root/components/hook-form/RHFDatePicker";
import { RHFUploadFile } from "@root/sections/carer-info/personal-info/application-form/basic-information/RHFUploadFile";
import SignaturePad from "@root/components/hook-form/SignaturePad";
import { RHFApiUploadFile } from "../RHFApiUploadFile";

export const defaultValues = {
  medalLevel: "gold",
  name: "",
  fromDate: new Date(),
  certificateAwarded: null,
  toDate: new Date(),
  outcome: "",
  outcomeNotes: "",
  assessmentBy: "",
  assessmentDate: new Date(),
  videoOrAudioEvidence: null,
  assessorDigitalSign: null,
  travelByBus: false,
  travelByBusEvidence: "",
  planJourneyByBus: false,
  planJourneyByBusEvidence: "",
  planJouknowAdultDailyNeedsrneyByBus: false,
  knowAdultDailyNeedsEvidence: "",
  contactAdultForEmergency: false,
  contactAdultForEmergencyEvidence: "",
  communicateWithFamily: false,
  communicateWithFamilyEvidence: "",
  savePocketMoney: false,
  savePocketMoneyEvidence: "",
  sendLetter: false,
  sendLetterEvidence: "",
  setupEmailAddress: false,
  setupEmailAddressEvidence: "",
  userComputerForHW: false,
  userComputerForHWEvidence: "",
  personalSafetyUsingComputer: false,
  personalSafetyUsingComputerEvidence: "",
  personalHygiene: false,
  personalHygieneEvidence: "",
  washHair: false,
  washHairEvidence: "",
  changeClothes: false,
  changeClothesEvidence: "",
  changeBedding: false,
  changeBeddingEvidence: "",
  useTumbleDryer: false,
  useTumbleDryerEvidence: "",
  useVacuumCleaner: false,
  useVacuumCleanerEvidence: "",
  canMakeSandwich: false,
  canMakeSandwichEvidence: "",
  canUseMircowave: false,
  canUseMircowaveEvidence: "",
  whereLocalBusStop: false,
  whereLocalBusStopEvidence: "",
  whereLocalShop: false,
  whereLocalShopEvidence: "",
  communicateWithSchoolTeachers: false,
  communicateWithSchoolTeachersEvidence: "",
  openedBankAccount: false,
  openedBankAccountEvidence: "",
  sendText: false,
  sendTextEvidence: "",
  protectFromCyberBullying: false,
  protectFromCyberBullyingEvidence: "",
  dangersOfSharingPersonalDetail: false,
  dangersOfSharingPersonalDetailEvidence: "",
  canHaveBath: false,
  canHaveBathEvidence: "",
  canCleanTeeth: false,
  canCleanTeethEvidence: "",
  canMakeBed: false,
  canMakeBedEvidence: "",
  useWashingMachine: false,
  useWashingMachineEvidence: "",
  canHangWashing: false,
  canHangWashingEvidence: "",
  cleaningAfterMakingDrinks: false,
  cleaningAfterMakingDrinksEvidence: "",
  canMakeCupOfTea: false,
  canMakeCupOfTeaEvidence: "",
  canUseGoodManners: false,
  canUseGoodMannersEvidence: "",
  commWithFriend: false,
  commWithFriendEvidence: "",
  // silver
  useTrain: false,
  useTrainEvidence: "",
  planJourneyByTrain: false,
  planJourneyByTrainEvidence: "",
  orderTaxi: false,
  orderTaxiEvidence: "",
  backToShop: false,
  backToShopEvidence: "",
  useOvenWithStaff: false,
  useOvenWithStaffEvidence: "",
  cookWithInstruction: false,
  cookWithInstructionEvidence: "",
  orderMealPay: false,
  orderMealPayEvidence: "",
  whyCleanKitchen: false,
  whyCleanKitchenEvidence: "",
  brushMopFloor: false,
  brushMopFloorEvidence: "",
  ironMyClothing: false,
  ironMyClothingEvidence: "",
  makeMedicalApp: false,
  makeMedicalAppEvidence: "",
  basicFirstAid: false,
  basicFirstAidEvidence: "",
  changeBulb: false,
  changeBulbEvidence: "",
  bookTicketAlone: false,
  bookTicketAloneEvidence: "",
  stayHealthyImportance: false,
  stayHealthyImportanceEvidence: "",
  understandDiffSexuality: false,
  understandDiffSexualityEvidence: "",
  commWithOtherPeople: false,
  commWithOtherPeopleEvidence: "",
  safeInRelationship: false,
  safeInRelationshipEvidence: "",
  studyForExam: false,
  studyForExamEvidence: "",
  whereToLookJob: false,
  whereToLookJobEvidence: "",
  interviewPreparation: false,
  interviewPreparationEvidence: "",
  purchaseTrainTicket: false,
  purchaseTrainTicketEvidence: "",
  renewBusPass: false,
  renewBusPassEvidence: "",
  saveUpForNeed: false,
  saveUpForNeedEvidence: "",
  planShoppingList: false,
  planShoppingListEvidence: "",
  prepFoodCorrectly: false,
  prepFoodCorrectlyEvidence: "",
  readFollowRecipe: false,
  readFollowRecipeEvidence: "",
  storeLeftOverSafely: false,
  storeLeftOverSafelyEvidence: "",
  cleanBathroomWithStaff: false,
  cleanBathroomWithStaffEvidence: "",
  understandMedicalNeeds: false,
  understandMedicalNeedsEvidence: "",
  selfAdministerBasicMed: false,
  selfAdministerBasicMedEvidence: "",
  canSeekMedicalEmergency: false,
  canSeekMedicalEmergencyEvidence: "",
  canChangePlug: false,
  canChangePlugEvidence: "",
  planJourneyWithComputer: false,
  planJourneyWithComputerEvidence: "",
  canLookForActivities: false,
  canLookForActivitiesEvidence: "",
  canUserSocialSite: false,
  canUserSocialSiteEvidence: "",
  adviceOnDrugsAndAlcohol: false,
  adviceOnDrugsAndAlcoholEvidence: "",
  seekHelpRegardingSexual: false,
  seekHelpRegardingSexualEvidence: "",
  goodRelationIs: false,
  goodRelationIsEvidence: "",
  understandDiffCulture: false,
  understandDiffCultureEvidence: "",
  shopWithinBudget: false,
  shopWithinBudgetEvidence: "",
  careerCollegAdvice: false,
  careerCollegAdviceEvidence: "",
  visitJobCentre: false,
  visitJobCentreEvidence: "",
  toDoAfterLeaveSchool: false,
  toDoAfterLeaveSchoolEvidence: "",
  ableToSaveUp: false,
  ableToSaveUpEvidence: "",
  completeCV: false,
  completeCVEvidence: "",
  renewBusTicket: false,
  renewBusTicketEvidence: "",
  basicLoanKnowledge: false,
  basicLoanKnowledgeEvidence: "",

  // gold
  getDriverLicense: false,
  getDriverLicenseEvidence: "",
  minorIllnessInjury: false,
  minorIllnessInjuryEvidence: "",
  useCookerAlone: false,
  useCookerAloneEvidence: "",
  organiseCleaningRoutine: false,
  organiseCleaningRoutineEvidence: "",
  differentHousingOptions: false,
  differentHousingOptionsEvidence: "",
  adultHelpWithHousing: false,
  adultHelpWithHousingEvidence: "",
  understandSavingMoney: false,
  understandSavingMoneyEvidence: "",
  knowCitizenAdviceInWarrington: false,
  knowCitizenAdviceInWarringtonEvidence: "",
  getPassport: false,
  getPassportEvidence: "",
  prepareSeveralBalancedMeal: false,
  prepareSeveralBalancedMealEvidence: "",
  houseHoldFireHazards: false,
  houseHoldFireHazardsEvidence: "",
  healthyRelationshipWithFriend: false,
  healthyRelationshipWithFriendEvidence: "",
  tenancyAgreement: false,
  tenancyAgreementEvidence: "",
  housingAndOtherBenefitForms: false,
  housingAndOtherBenefitFormsEvidence: "",
  leavingCareAllowance: false,
  leavingCareAllowanceEvidence: "",
  experienceFinancialDifficulties: false,
  experienceFinancialDifficultiesEvidence: "",
};

export const FormSchema = Yup.object().shape({
  name: Yup.string().required("Field is required"),
  fromDate: Yup.date().required("Date of Interview is required"),
  certificateAwarded: Yup.mixed().nullable().required("Field is required"),
  toDate: Yup.date()
    .min(Yup.ref("fromDate"), "to date can't be before from date")
    .required("Date of Interview is required"),
  outcome: Yup.string().required("Field is required"),
  outcomeNotes: Yup.string().required("Field is required"),
  assessmentBy: Yup.string().required("Field is required"),
  assessmentDate: Yup.date().required("Field of Interview is required"),
  videoOrAudioEvidence: Yup.mixed().nullable().required("Field is required"),
  assessorDigitalSign: Yup.mixed().nullable().required("Field is required"),
});
export const formData1 = [
  {
    gridLength: 6,
    otherOptions: {
      name: "toDate",
      label: "To Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "certificateAwarded",
      label: "Certificate Awarded",
      fullWidth: true,
      size: "small",
    },
    component: RHFUploadFile,
  },
];
export const formData2 = [
  {
    gridLength: 6,
    otherOptions: {
      name: "outcome",
      label: "Outcome",
      fullWidth: true,
      select: true,
    },
    options: [
      { value: "Pakistan", label: "Pakistan" },
      { value: "India", label: "India" },
      { value: "areaOffice information", label: "areaOffice information" },
    ],
    component: RHFSelect,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "outcomeNotes",
      label: "Outcome Notes/Comments",
      multiline: true,
      minRows: 3,
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "assessmentBy",
      label: "Accessment done by",
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "assessmentDate",
      label: "Accessment Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "assessorDigitalSign",
      label: "Signature Of Accessor",
      sx: { marginTop: "-20px" },
    },
    component: SignaturePad,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "videoOrAudioEvidence",
      label: "Attach Video/Audio Evidence",
      fullWidth: true,
      size: "small",
    },
    component: RHFUploadFile,
  },
];
export const ListOfSkills = [
  {
    gridLength: 12,
    otherOptions: {
      name: "orderTaxi",
      label: "I can travel alone on train, bus and taxi.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "orderTaxiEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "getDriverLicense",
      label: "I know how to get a driver’s licence.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "getDriverLicenseEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "makeMedicalApp",
      label:
        "I can attend all my medical appointments alone and know how to collect prescriptions from the chemist.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "makeMedicalAppEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "minorIllnessInjury ",
      label: "I know how to take care of minor illness and injuries.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "minorIllnessInjuryEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "useCookerAlone",
      label: "I can use the cooker alone.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "useCookerAloneEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "organiseCleaningRoutine",
      label:
        "I can organise a cleaning routine and evidence I can stick to it.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "organiseCleaningRoutineEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
    },
    component: RHFUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "differentHousingOptions",
      label: "I understand the different housing options open to me. ",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "differentHousingOptionsEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "adultHelpWithHousing",
      label:
        "I know an adult who can help and advise me with housing or other benefits I may need to claim.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "adultHelpWithHousingEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "understandSavingMoney",
      label: "I understand ways of saving money.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "understandSavingMoneyEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },

  {
    gridLength: 12,
    otherOptions: {
      name: "knowCitizenAdviceInWarrington",
      label:
        "I know what citizens advice is for and where it is located in Warrington.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "knowCitizenAdviceInWarringtonEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
];
export const ListOfSkillsWithEvidence = [
  {
    gridLength: 12,
    otherOptions: {
      name: "renewBusPass",
      label: "I can renew my bus pass alone.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "renewBusPassEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "getPassport",
      label: "I know how to get a passport.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "getPassportEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "understandMedicalNeeds",
      label:
        "I understand my medical needs and take all my own medication correctly without help.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "understandMedicalNeedsEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "prepareSeveralBalancedMeal",
      label:
        "I am able to prepare several well balanced meals from fresh ingredients on my own.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "prepareSeveralBalancedMealEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "houseHoldFireHazards",
      label:
        "I understand the importance of household safety eg fire hazards, gas, and electrical.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "houseHoldFireHazardsEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "healthyRelationshipWithFriend",
      label:
        "I can evidence I have healthy relationships with friends and can maintain them.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "healthyRelationshipWithFriendEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "tenancyAgreement",
      label: "I have seen a tenancy agreement.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "tenancyAgreementEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "housingAndOtherBenefitForms",
      label:
        "I have seen the housing and other benefit forms I may need to complete.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "housingAndOtherBenefitFormsEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "leavingCareAllowance",
      label:
        "I understand my leaving care allowance, and what it is to be used for.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "leavingCareAllowanceEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "experienceFinancialDifficulties",
      label: "I know where to go if I experience financial difficulties.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "experienceFinancialDifficultiesEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
];
