export const statsData = [
  {
    sx: {
      width: "100px",
      height: "100px",
      position: "relative",
      mt: "36px",
      mr: "-20px",
      color: "#C84C0F",
      borderWidth: "8px",
    },
    titleSx: { fontWeight: 400, fontSize: "14px" },
    title: "rejected",
    count: 100,
  },
  {
    sx: {
      width: "140px",
      height: "140px",
      position: "relative",
      mt: "65px",
      zIndex: 1,
      mr: "-2px",
      color: "#5BA316",
      borderWidth: "12px",
    },
    titleSx: { fontWeight: 600, fontSize: "18px" },
    title: "approved",
    count: 100,
  },
  {
    sx: {
      width: "180px",
      height: "180px",
      position: "relative",
      color: "#4A797E",
      mt: "-40px",
      ml: "-35px",
      zIndex: 10,
      borderWidth: "12px",
    },
    titleSx: { fontWeight: 600, fontSize: "18px" },
    title: "placed referral",
    count: 100,
  },
  {
    sx: {
      width: "98px",
      height: "98px",
      position: "relative",
      mt: "69px",
      ml: "-25px",
      color: "#849399",
      zIndex: 3,
      borderWidth: "8px",
    },
    titleSx: { fontWeight: 400, fontSize: "14px" },
    title: "blacklist",
    count: 100,
  },
  {
    sx: {
      width: "121px",
      height: "121px",
      position: "relative",
      mt: "-40px",
      ml: "-87px",
      color: "#E07601",
      zIndex: 2,
      borderWidth: "12px",
    },
    titleSx: { fontWeight: 600, fontSize: "16px" },
    title: "on hold",
    count: 100,
  },
  {
    sx: {
      width: "110px",
      height: "110px",
      position: "relative",
      mt: "40px",
      ml: "-45px",
      color: "#FFB600",
      borderWidth: "8px",
    },
    titleSx: { fontWeight: 400, fontSize: "14px" },
    title: "requested",
    count: 100,
  },
];
