export const TableDemoData = [
  {
    id: 1,
    sNO: "1",
    primayCarerName: "Jamie",
    secondaryCarerName: "John Doe ",
    fosterCarerAddress:"uxbridg UB111W",
    approvalDate:"04/11/2021",
    approvalCategory:"00-03 Either Gender",
    childrenName:"2",
    immigrationStatus:"Approved",
    placementType:"26/12/2021",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedBy: "John Doe",
  },
  {
    id: 2,
    sNO: "2",
    primayCarerName: "Timmy Toppee",
    secondaryCarerName: "Harriet Upp  ",
    fosterCarerAddress:"uxbridg UB111W",
    approvalDate:"04/11/2021",
    approvalCategory:"00-03 Either Gender",
    childrenName:"2",
    immigrationStatus:"In progress",
    placementType:"26/12/2021",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedBy: "John Doe",
 
  },
  {
    id: 3,
    sNO: "3",
    primayCarerName: "Timmy Toppee",
    secondaryCarerName: "Name Xame ",
    fosterCarerAddress:"uxbridg UB111W",
    approvalDate:"04/11/2021",
    approvalCategory:"00-03 Either Gender",
    childrenName:"2",
    immigrationStatus:"Approved",
    placementType:"26/12/2021",
    createdDate: "12/10/2021",
    createdBy: "RoseMarry",
    modifiedDate: "26/12/2021",
    modifiedBy: "John Doe",
  }
];