export const tabs = [
  {
    name: "ABOUT THE CANDIDATE",
    limit: [0, 4],
  },
  { name: "REFERENCES", limit: [4, 5] },
  {
    name: "TRAINING & WORK HISTORY",
    limit: [5, 9],
  },
  {
    name: "BACKGROUND CHECKS",
    limit: [9, 11],
  },
  {
    name: "OTHER INFORMATION",
    limit: [11, 17],
  },
  {
    name: "MEDICAL HISTORY",
    limit: [17, 19],
  },
  {
    name: "DECLARATION",
    limit: [19, 20],
  },
];

export const tabsItems = [
  { name: "Personal Info", status: "In Progress" },
  { name: "Address Details", status: "Done" },
  { name: "Photo for ID Badge", status: "In Progress" },
  { name: "ID Upload (Passport/DL)", status: "Done" },
  { name: "Add Reference", status: "Done" },
  { name: "Training Certificates", status: "Done" },
  { name: "Additional Training Details", status: "Done" },
  { name: "Work Experience", status: "Done" },
  { name: "Specialities", status: "Done" },
  { name: "DBS", status: "Done" },
  { name: "Right to work", status: "Done" },
  { name: "Next Of kin", status: "Done" },
  { name: "Contact Preference", status: "Done" },
  { name: "Employment Status", status: "Done" },
  { name: "Opportunity Declaration", status: "Done" },
  { name: "Additional Docs", status: "Done" },
  { name: "Bank Details", status: "Done" },
  { name: "Immunisation", status: "Done" },
  { name: "Medical Questionnaire", status: "Done" },
  { name: "Add Declaration", status: "Done" },
];

export const localFormNames = [
  "Personal Info",
  "personalInfo",
  "Address Details",
  "addressdetail",
  "Photo for ID Badge",
  "badgeId",
  "ID Upload (Passport/DL)",
  "passport",
  "Add Reference",
  "reference",
  "Training Certificates",
  "trainingCertificate",
  "Additional Training Details",
  "trainingDetail",
  "Work Experience",
  "workExperience",
  "Specialities",
  "specialities",
  "DBS",
  "dbs",
  "Right to work",
  "workRight",
  "Next Of kin",
  "nextOfKim",
  "Contact Preference",
  "contactPreferance",
  "Employment Status",
  "employmentStatus",
  "Opportunity Declaration",
  "opportunityDeclaration",
  "Additional Docs",
  "documents",
  "Bank Details",
  "bankDetail",
  "Immunisation",
  "immunisation",
  "Medical Questionnaire",
  "questionair",
  "Add Declaration",
  "declaration",
];
