import EditIcon from "../../../../assets/svg/safeguarding/edit.svg";
import ShareIcon from "../../../../assets/svg/safeguarding/share.svg";
import EmailIcon from "../../../../assets/svg/safeguarding/Email.svg";
import PhoneIcon from "../../../../assets/svg/safeguarding/Phone.svg";
import DeleteIcon from "../../../../assets/svg/safeguarding/delete.svg";
import WhatsApp from "../../../../assets/svg/safeguarding/whatsapp.svg";
import InactiveLock from "../../../../assets/svg/safeguarding/inactiveLock.svg";

// ============================================================================================

export const tableActionIcons = [
  { type: "edit", id: "edit", img: EditIcon },
  { type: "inactiveLock", id: "inactiveLock", img: InactiveLock },
  { type: "share", id: "share", img: ShareIcon },
  { type: "delete", id: "delete", img: DeleteIcon },
  { type: "phone", id: "phone", img: PhoneIcon },
  { type: "email", id: "email", img: EmailIcon },
  { type: "whatsapp", id: "whatsapp", img: WhatsApp },
];

// ==================================================================================================

export const tableData = [
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "#b0d6e3",
  },
  {
    name: "Bob Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Alberto Delrio",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "England",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
  {
    name: "Beth Cooper",
    role: "Foster Carer",
    safeguardingRole: "Fostering",
    branch: "Manchester",
    businessPhone: "0215648545",
    email: "Albertodel@fosterapp.com",
    mobile: "441369987261",
    company: "-",
    address: "Dunedin Road, London",
    postCode: "E10 5PE",
    country: "",
    colorCode: "",
  },
];
