import {
  RHFCheckbox,
  RHFSelect,
  RHFTextField,
} from "@root/components/hook-form";
import * as Yup from "yup";
import RHFDatePicker from "@root/components/hook-form/RHFDatePicker";
import { RHFUploadFile } from "@root/sections/carer-info/personal-info/application-form/basic-information/RHFUploadFile";
import SignaturePad from "@root/components/hook-form/SignaturePad";
import { RHFApiUploadFile } from "../RHFApiUploadFile";

export const defaultValues = {
  medalLevel: "bronze",
  name: "",
  fromDate: new Date(),
  certificateAwarded: null,
  toDate: new Date(),
  outcome: "",
  outcomeNotes: "",
  assessmentBy: "",
  assessmentDate: new Date(),
  videoOrAudioEvidence: null,
  assessorDigitalSign: null,
  travelByBus: false,
  travelByBusEvidence: "",
  planJourneyByBus: false,
  planJourneyByBusEvidence: "",
  planJouknowAdultDailyNeedsrneyByBus: false,
  knowAdultDailyNeedsEvidence: "",
  contactAdultForEmergency: false,
  contactAdultForEmergencyEvidence: "",
  communicateWithFamily: false,
  communicateWithFamilyEvidence: "",
  savePocketMoney: false,
  savePocketMoneyEvidence: "",
  sendLetter: false,
  sendLetterEvidence: "",
  setupEmailAddress: false,
  setupEmailAddressEvidence: "",
  userComputerForHW: false,
  userComputerForHWEvidence: "",
  personalSafetyUsingComputer: false,
  personalSafetyUsingComputerEvidence: "",
  personalHygiene: false,
  personalHygieneEvidence: "",
  washHair: false,
  washHairEvidence: "",
  changeClothes: false,
  changeClothesEvidence: "",
  changeBedding: false,
  changeBeddingEvidence: "",
  useTumbleDryer: false,
  useTumbleDryerEvidence: "",
  useVacuumCleaner: false,
  useVacuumCleanerEvidence: "",
  canMakeSandwich: false,
  canMakeSandwichEvidence: "",
  canUseMircowave: false,
  canUseMircowaveEvidence: "",
  whereLocalBusStop: false,
  whereLocalBusStopEvidence: "",
  whereLocalShop: false,
  whereLocalShopEvidence: "",
  communicateWithSchoolTeachers: false,
  communicateWithSchoolTeachersEvidence: "",
  openedBankAccount: false,
  openedBankAccountEvidence: "",
  sendText: false,
  sendTextEvidence: "",
  protectFromCyberBullying: false,
  protectFromCyberBullyingEvidence: "",
  dangersOfSharingPersonalDetail: false,
  dangersOfSharingPersonalDetailEvidence: "",
  canHaveBath: false,
  canHaveBathEvidence: "",
  canCleanTeeth: false,
  canCleanTeethEvidence: "",
  canMakeBed: false,
  canMakeBedEvidence: "",
  useWashingMachine: false,
  useWashingMachineEvidence: "",
  canHangWashing: false,
  canHangWashingEvidence: "",
  cleaningAfterMakingDrinks: false,
  cleaningAfterMakingDrinksEvidence: "",
  canMakeCupOfTea: false,
  canMakeCupOfTeaEvidence: "",
  canUseGoodManners: false,
  canUseGoodMannersEvidence: "",
  commWithFriend: false,
  commWithFriendEvidence: "",
  // silver
  useTrain: false,
  useTrainEvidence: "",
  planJourneyByTrain: false,
  planJourneyByTrainEvidence: "",
  orderTaxi: false,
  orderTaxiEvidence: "",
  backToShop: false,
  backToShopEvidence: "",
  useOvenWithStaff: false,
  useOvenWithStaffEvidence: "",
  cookWithInstruction: false,
  cookWithInstructionEvidence: "",
  orderMealPay: false,
  orderMealPayEvidence: "",
  whyCleanKitchen: false,
  whyCleanKitchenEvidence: "",
  brushMopFloor: false,
  brushMopFloorEvidence: "",
  ironMyClothing: false,
  ironMyClothingEvidence: "",
  makeMedicalApp: false,
  makeMedicalAppEvidence: "",
  basicFirstAid: false,
  basicFirstAidEvidence: "",
  changeBulb: false,
  changeBulbEvidence: "",
  bookTicketAlone: false,
  bookTicketAloneEvidence: "",
  stayHealthyImportance: false,
  stayHealthyImportanceEvidence: "",
  understandDiffSexuality: false,
  understandDiffSexualityEvidence: "",
  commWithOtherPeople: false,
  commWithOtherPeopleEvidence: "",
  safeInRelationship: false,
  safeInRelationshipEvidence: "",
  studyForExam: false,
  studyForExamEvidence: "",
  whereToLookJob: false,
  whereToLookJobEvidence: "",
  interviewPreparation: false,
  interviewPreparationEvidence: "",
  purchaseTrainTicket: false,
  purchaseTrainTicketEvidence: "",
  renewBusPass: false,
  renewBusPassEvidence: "",
  saveUpForNeed: false,
  saveUpForNeedEvidence: "",
  planShoppingList: false,
  planShoppingListEvidence: "",
  prepFoodCorrectly: false,
  prepFoodCorrectlyEvidence: "",
  readFollowRecipe: false,
  readFollowRecipeEvidence: "",
  storeLeftOverSafely: false,
  storeLeftOverSafelyEvidence: "",
  cleanBathroomWithStaff: false,
  cleanBathroomWithStaffEvidence: "",
  understandMedicalNeeds: false,
  understandMedicalNeedsEvidence: "",
  selfAdministerBasicMed: false,
  selfAdministerBasicMedEvidence: "",
  canSeekMedicalEmergency: false,
  canSeekMedicalEmergencyEvidence: "",
  canChangePlug: false,
  canChangePlugEvidence: "",
  planJourneyWithComputer: false,
  planJourneyWithComputerEvidence: "",
  canLookForActivities: false,
  canLookForActivitiesEvidence: "",
  canUserSocialSite: false,
  canUserSocialSiteEvidence: "",
  adviceOnDrugsAndAlcohol: false,
  adviceOnDrugsAndAlcoholEvidence: "",
  seekHelpRegardingSexual: false,
  seekHelpRegardingSexualEvidence: "",
  goodRelationIs: false,
  goodRelationIsEvidence: "",
  understandDiffCulture: false,
  understandDiffCultureEvidence: "",
  shopWithinBudget: false,
  shopWithinBudgetEvidence: "",
  careerCollegAdvice: false,
  careerCollegAdviceEvidence: "",
  visitJobCentre: false,
  visitJobCentreEvidence: "",
  toDoAfterLeaveSchool: false,
  toDoAfterLeaveSchoolEvidence: "",
  ableToSaveUp: false,
  ableToSaveUpEvidence: "",
  completeCV: false,
  completeCVEvidence: "",
  renewBusTicket: false,
  renewBusTicketEvidence: "",
  basicLoanKnowledge: false,
  basicLoanKnowledgeEvidence: "",

  // gold
  getDriverLicense: false,
  getDriverLicenseEvidence: "",
  minorIllnessInjury: false,
  minorIllnessInjuryEvidence: "",
  useCookerAlone: false,
  useCookerAloneEvidence: "",
  organiseCleaningRoutine: false,
  organiseCleaningRoutineEvidence: "",
  differentHousingOptions: false,
  differentHousingOptionsEvidence: "",
  adultHelpWithHousing: false,
  adultHelpWithHousingEvidence: "",
  understandSavingMoney: false,
  understandSavingMoneyEvidence: "",
  knowCitizenAdviceInWarrington: false,
  knowCitizenAdviceInWarringtonEvidence: "",
  getPassport: false,
  getPassportEvidence: "",
  prepareSeveralBalancedMeal: false,
  prepareSeveralBalancedMealEvidence: "",
  houseHoldFireHazards: false,
  houseHoldFireHazardsEvidence: "",
  healthyRelationshipWithFriend: false,
  healthyRelationshipWithFriendEvidence: "",
  tenancyAgreement: false,
  tenancyAgreementEvidence: "",
  housingAndOtherBenefitForms: false,
  housingAndOtherBenefitFormsEvidence: "",
  leavingCareAllowance: false,
  leavingCareAllowanceEvidence: "",
  experienceFinancialDifficulties: false,
  experienceFinancialDifficultiesEvidence: "",
};

export const FormSchema = Yup.object().shape({
  name: Yup.string().required("Field is required"),
  fromDate: Yup.date().required("Date of Interview is required"),
  certificateAwarded: Yup.mixed().nullable().required("Field is required"),
  toDate: Yup.date()
    .min(Yup.ref("fromDate"), "to date can't be before from date")
    .required("Date of Interview is required"),
  outcome: Yup.string().required("Field is required"),
  outcomeNotes: Yup.string().required("Field is required"),
  assessmentBy: Yup.string().required("Field is required"),
  assessmentDate: Yup.date().required("Field of Interview is required"),
  videoOrAudioEvidence: Yup.mixed().nullable().required("Field is required"),
  assessorDigitalSign: Yup.mixed().nullable().required("Field is required"),
});
export const formData1 = [
  {
    gridLength: 6,
    otherOptions: {
      name: "toDate",
      label: "To Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "certificateAwarded",
      label: "Certificate Awarded",
      fullWidth: true,
      size: "small",
    },
    component: RHFUploadFile,
  },
];
export const formData2 = [
  {
    gridLength: 6,
    otherOptions: {
      name: "outcome",
      label: "Outcome",
      fullWidth: true,
      select: true,
    },
    options: [
      { value: "Pakistan", label: "Pakistan" },
      { value: "India", label: "India" },
      { value: "areaOffice information", label: "areaOffice information" },
    ],
    component: RHFSelect,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "outcomeNotes",
      label: "Outcome Notes/Comments",
      multiline: true,
      minRows: 3,
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "assessmentBy",
      label: "Accessment done by",
      fullWidth: true,
    },
    component: RHFTextField,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "assessmentDate",
      label: "Accessment Date",
      fullWidth: true,
    },
    component: RHFDatePicker,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "assessorDigitalSign",
      label: "Signature Of Accessor",
      sx: { marginTop: "-20px" },
    },
    component: SignaturePad,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "videoOrAudioEvidence",
      label: "Attach Video/Audio Evidence",
      fullWidth: true,
      size: "small",
    },
    component: RHFUploadFile,
  },
];
export const ListOfSkills = [
  {
    gridLength: 12,
    otherOptions: {
      name: "travelByBus",
      label: "I can travel by bus",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "travelByBusEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "planJourneyByBus",
      label: "I can use a bus time to plan a journey",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "planJourneyByBusEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "planJouknowAdultDailyNeedsrneyByBus",
      label: "I know an adult who i can trust with my daily needs",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "knowAdultDailyNeedsEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "contactAdultForEmergency",
      label:
        "I can contact emergency services, police, fire, ambulance and fire brigade",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "contactAdultForEmergencyEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "communicateWithFamily",
      label: "I can communicate with my family and know when I need staff help",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "communicateWithFamilyEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "savePocketMoney",
      label:
        "I can save up some of my pocket money to buy a larger item I want",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "savePocketMoneyEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "sendLetter",
      label: "I can send a letter",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "sendLetterEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "setupEmailAddress",
      label: "I know how to set up an e-mail address",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "setupEmailAddressEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "userComputerForHW",
      label:
        "I know how to use a computer to complete my homework with the help of staff",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "userComputerForHWEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "personalSafetyUsingComputer",
      label: "I understand personal safety when using the computer",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "personalSafetyUsingComputerEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "personalHygiene",
      label:
        "I have good personal hygiene and understand why this is important",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "personalHygieneEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "washHair",
      label: "I can wash my hair",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "washHairEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "changeClothes",
      label: "I know when to change my clothes",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "changeClothesEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "changeBedding",
      label: "I can change my bedding",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "changeBeddingEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "useTumbleDryer",
      label: "I can use the tumble dryer with staff help",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "useTumbleDryerEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "useVacuumCleaner",
      label: "I know how to use the vacuum cleaner",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "useVacuumCleanerEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canMakeSandwich",
      label: "I can make a sandwich",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canMakeSandwichEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canUseMircowave",
      label: "I can use the microwave.",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canUseMircowaveEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
];
export const ListOfSkillsWithEvidence = [
  {
    gridLength: 12,
    otherOptions: {
      name: "whereLocalBusStop",
      label: "I know where the local bus stop is to take me town",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "whereLocalBusStopEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "whereLocalShop",
      label: "I know where the local shop is",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "whereLocalShopEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "contactAdultForEmergency",
      label: "I know an adult who I can contact in case of emergency",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "contactAdultForEmergencyEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "communicateWithSchoolTeachers",
      label:
        "I know how to communicate with teachers in school with staffs help",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "communicateWithSchoolTeachersEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "commWithFriend",
      label:
        "I can communicate with my friends and know when I need staff help",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "commWithFriendEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "openedBankAccount",
      label: "I have opened a bank account",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "openedBankAccountEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "sendText",
      label: "I can send a text",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "sendTextEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },

  {
    gridLength: 12,
    otherOptions: {
      name: "protectFromCyberBullying",
      label: "I am able to keep myself safe from cyber bullying",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "protectFromCyberBullyingEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "dangersOfSharingPersonalDetail",
      label: "I understand the dangers of giving out personal details on line",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "dangersOfSharingPersonalDetailEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canHaveBath",
      label: "I can have a bath",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canHaveBathEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canCleanTeeth",
      label: "I can clean my teeth",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canCleanTeethEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canMakeBed",
      label: "I can make my bed",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canMakeBedEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "useWashingMachine",
      label: "I can use the washing machine with staffs help",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "useWashingMachineEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canHangWashing",
      label: "I can hang my washing on the line",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canHangWashingEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "cleaningAfterMakingDrinks",
      label: "I can clean up after making drinks and snacks",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "cleaningAfterMakingDrinksEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canMakeCupOfTea",
      label: "I can make a cup of tea",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canMakeCupOfTeaEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
  {
    gridLength: 12,
    otherOptions: {
      name: "canUseGoodManners",
      label:
        "I can use good manners and show appreciate behaviours in a restaurant",
    },
    component: RHFCheckbox,
  },
  {
    gridLength: 6,
    otherOptions: {
      name: "canUseGoodMannersEvidence",
      label: "My Evidence",
      fullWidth: true,
      size: "small",
      file: true,
    },
    component: RHFApiUploadFile,
  },
];
