export const tableMockData = [
  {
    id: "1",
    srNo: "1",
    dob: "10/04/2000",
    nameFosteredYoungPerson: "Timmy Toppee",
    supervisingSocialWorker: "Anne Teak",
    fosterCarer: "Teri Dactyl",
    createdDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "10/03/23",
    modifiedBy: "John Doe",
  },
  {
    id: "1",
    srNo: "1",
    dob: "10/04/2000",
    nameFosteredYoungPerson: "Timmy Toppee",
    supervisingSocialWorker: "Anne Teak",
    fosterCarer: "Teri Dactyl",
    createdDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "10/03/23",
    modifiedBy: "John Doe",
  },
  {
    id: "1",
    srNo: "1",
    dob: "10/04/2000",
    nameFosteredYoungPerson: "Timmy Toppee",
    supervisingSocialWorker: "Anne Teak",
    fosterCarer: "Teri Dactyl",
    createdDate: "03/10/21",
    createdBy: "john doe",
    modifiedDate: "10/03/23",
    modifiedBy: "John Doe",
  },
];
