import { RHFSelect, RHFTextField } from "@root/components/hook-form";
import RHFDatePicker from "@root/components/hook-form/RHFDatePicker";
import RHFRadioGroupBoolean from "@root/components/hook-form/RHFRadioGroupBoolean";
import * as Yup from "yup";

export const delegatedAuthorityFormFields = [
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "consentToRoutine",
        label: "Consent to routine immunisationsvvvvvvvvvv",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 3,
      gridLength: 6,
      otherOptions: {
        name: "plannedMedicalProcedures",
        label: "Planned medical procedures",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 4,
      gridLength: 6,
      otherOptions: {
        name: "medicalProceduresCarriers",
        label:
          "Medical procedures carries out in the home where the administering the procedure requires training (e.g. child with disabilities / illness",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 5,
      gridLength: 6,
      otherOptions: {
        name: "dentalSignedConsent",
        label: "Dental - signed consent to dental emergency treatment (including anaesthetic)",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 6,
      gridLength: 6,
      otherOptions: {
        name: "dentalRoutineTreatment",
        label: "Dental - routine treatment (including anaesthetic)",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 6,
      gridLength: 6,
      otherOptions: {
        name: "opticianAppointments",
        label: "Optician - appointments, glasses",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 7,
      gridLength: 6,
      otherOptions: {
        name: "consentToExamination",
        label: "Consent to examination / treatment by school doctor / nurse",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 8,
      gridLength: 6,
      otherOptions: {
        name: "signedConsentDaySchoolTrips",
        label: "Signed consent for school trips - days",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 9,
      gridLength: 6,
      otherOptions: {
        name: "signedConsentOvernightSchoolTrips",
        label: "Signed consent for school trips - overnight",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 10,
      gridLength: 6,
      otherOptions: {
        name: "schoolTripsAbroad",
        label: "School trips abroad",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "changingRegisteringSchool",
        label: "Changing / registering at a school",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "lifeHistoryWork",
        label: "Life history work",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "overnightWithFriends",
        label: "Overnight with friends (sleepover)",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "holidayInBritain",
        label: "Holiday in Britain",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "holidayOutsideBritain",
        label: "Holiday outside Britain",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "sportsSocialClubs",
        label: "Sports / social clubs",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "hairCutsColouring",
        label: "Hair cuts / Colouring",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "bodyPiercing",
        label: "Body piercing",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "mobilePhone",
        label: "Mobile Phone",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "accessingSocialMedia",
        label: "Accessing social media - Facebook, Twitter, Instagram etc",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "attendanceAtWorshipPlace",
        label: "Attendance at a place of worship",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
    {
      id: 2,
      gridLength: 6,
      otherOptions: {
        name: "provideReligiousItems",
        label: "provide items needed to meet their religious needs",
        fullWidth: true,
        select: true,
      },
      options: [{ value: "nil", label: "nil" }],
      component: RHFSelect,
    },
  ];
  export const delegatedAuthorityDefaultValues = {
    consentToRoutine: null,
    plannedMedicalProcedures: null,
    medicalProceduresCarriers: null,
    dentalSignedConsent: null,
    dentalRoutineTreatment: null,
    opticianAppointments: null,
    consentToExamination: null,
    signedConsentDaySchoolTrips: null,
    signedConsentOvernightSchoolTrips: null,
    schoolTripsAbroad: null,
    changingRegisteringSchool: null,
    lifeHistoryWork: null,
    overnightWithFriends: null,
    holidayInBritain: null,
    holidayOutsideBritain: null,
    sportsSocialClubs: null,
    hairCutsColouring: null,
    bodyPiercing: null,
    mobilePhone: null,
    accessingSocialMedia: null,
    attendanceAtWorshipPlace: null,
    provideReligiousItems: null,
  };
  
  export const formatters: any = {};